// src/app/app.component.ts
import { Component } from '@angular/core';
import { RouterLink, RouterOutlet } from '@angular/router';
import { IGX_NAVBAR_DIRECTIVES, IgxAvatarComponent, IgxButtonDirective, IgxOverlayOutletDirective, IgxRippleDirective, IgxToggleActionDirective, IgxToggleDirective } from 'igniteui-angular';

@Component({
  selector: 'app-root',
  imports: [RouterLink, RouterOutlet, IGX_NAVBAR_DIRECTIVES, IgxAvatarComponent, IgxButtonDirective, IgxOverlayOutletDirective, IgxRippleDirective, IgxToggleActionDirective, IgxToggleDirective],
  templateUrl: './app.component.html',
  styleUrls: ['./app.component.scss']
})
export class AppComponent {
}

<igx-navbar class="navbar">
  <igx-navbar-title class="navbar-content">
    <igx-avatar src="/assets/Logo.svg" shape="circle" class="avatar"></igx-avatar>
    <button igxButton="flat" type="button" igxRipple routerLink="/view1" class="button">
      View 1
    </button>
    <button igxButton="flat" type="button" igxRipple routerLink="/view2" class="button">
      View 2
    </button>
    <button igxButton="flat" type="button" igxRipple routerLink="/view3" class="button">
      View 3
    </button>
  </igx-navbar-title>
</igx-navbar>
<div class="view-container">
  <router-outlet></router-outlet>
</div>

// src/app/app.tsx
import { IgrAvatar, IgrAvatarModule, IgrButton, IgrButtonModule, IgrNavbar, IgrNavbarModule, IgrRipple, IgrRippleModule } from 'igniteui-react';
import { Outlet, useNavigate } from 'react-router-dom';
import styles from './app.module.css';
import createClassTransformer from './style-utils';

IgrAvatarModule.register();
IgrButtonModule.register();
IgrNavbarModule.register();
IgrRippleModule.register();

export default function App() {
  const classes = createClassTransformer(styles);
  const uuid = () => crypto.randomUUID();
  const navigate = useNavigate();

  return (
    <>
      <div className={classes("column-layout master-view-container")}>
        <IgrNavbar className={classes("navbar")}>
          <div className={classes("row-layout group")} key={uuid()}>
            <IgrAvatar src="/src/assets/Logo.svg" shape="circle" className={classes("avatar")}></IgrAvatar>
            <IgrButton variant="flat" type="button" clicked={() => navigate(`/view1`)} className={classes("button")}>
              <span key={uuid()}>View 1</span>
              <IgrRipple key={uuid()}></IgrRipple>
            </IgrButton>
            <IgrButton variant="flat" type="button" clicked={() => navigate(`/view2`)} className={classes("button")}>
              <span key={uuid()}>View 2</span>
              <IgrRipple key={uuid()}></IgrRipple>
            </IgrButton>
            <IgrButton variant="flat" type="button" clicked={() => navigate(`/view3`)} className={classes("button")}>
              <span key={uuid()}>View 3</span>
              <IgrRipple key={uuid()}></IgrRipple>
            </IgrButton>
          </div>
        </IgrNavbar>
        <div className={classes("view-container")}>
          <Outlet></Outlet>
        </div>
      </div>
    </>
  );
}
